[[renditions]]
= Renditions

== Overview

When enabled, renditions give stores the ability to transform content from one format to another by providing a small
set of renderers out-of-the-box.

It also provides an extension point for providing your own renderers.

To enable renditions add the `spring-content-renditions` or `spring-content-renditions-boot-starter` dependency to your
project.  This enables the renditions capability and a small set of renderers that can convert documents of various
types to jpeg images based on the apache poi and pdfbox libraries

You can also add the `spring-content-docx4j` dependency to your project for an additional small set of renderers that
can convert documents between Microsoft Word, Adobe PDF and HTML based on the docx4j library.

== Maven Central Coordinates
The maven coordinates for this Spring Content library are as follows:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-renditions</artifactId>
</dependency>
```

As it is usual to use several Spring Content libraries together importing the bom is recommended:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-bom</artifactId>
    <version>${spring-content-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

== Annotation-based Configuration

.Enabling Spring Content Renditions with Java Config
====
[source, java]
----
@Configuration
@Import(org.springframework.content.renditions.config.RenditionsConfiguration.class) <1>
@Import(org.springframework.content.docx4j.config.Docx4jConfiguration.class)         <2>
public static class ApplicationConfig {
}
----
1. Not required when using `spring-content-renditions-boot-starter`
2. Not required when using `spring-content-renditions-boot-starter`
====

== Making Stores Renderable

With renditions enabled, Store interfaces can be made `Renderable`.  See
<<content-repositories.renditions,Renderable Stores>> for more information on how to do this.

== Renderers

The `spring-content-rendition` dependency contributes the following renderer:

- Pdf To Jpeg
- Text To Jpeg
- Word To Jpeg
- Jpeg To Png

The `spring-content-docx4j` dependency contributes the following renderer:

- Word To Html
- Word To PDF
- Word To Text

== RenditionProvider Extension Point

Spring Content Renditions offers some common renderers out-of-the-box.  However, if you need to provide additional
renderers to satisfy your use cases then you can implement the RenditionProvider extension point.  This requires you
to implement the `RenditionProvider` interface, mark this implementation as a `@Service` and ensure that it is
contributed as a bean to your application context at runtime.

.Implementing the RenditionProvider Extension Point
====
[source, java]
----
package my.custom.rendition.provider;

@Service    <2>
public class CustomRenditionProvider implements RenditionProvider { <1>

	@Override
	public String consumes() {
		return "my/type";
	}

	@Override
	public String[] produces() {
		return new String[] { "your/type" };
	}

	@Override
	public InputStream convert(InputStream fromInputSource, String toMimeType) {
}

...

@Configuration
@ComponentScan("my.custom.rendition.provider")         <3>
public static class ApplicationConfig {
}
----
1. Implementation of `RenditionProvider`
2. Marked as an `@Service`
3. Ensure the service is scanned by Spring and offered as a bean
====

== RenditionProvider Extension Point for Alfresco ECM

Spring Content supports the renditions integration with the https://docs.alfresco.com/transform-service/latest/[Alfresco Transform Core] service.
When the `spring-content-renditions` (or `spring-content-renditions-boot-starter`) dependency is included, you can add the RenditionProvider list from Alfresco
Transform Service simply adding the property `alfresco.transform.core.url` on your application.properties.

This mechanism, allows the creation of `AlfrescoTransformCoreRenditionProviderLoader` bean that:

1. Check if the service is up;
2. If it's running, the `AlfrescoTransformCoreRenditionProviderLoader` register a bean of type RenditionProvider for each transformer found on the Alfresco Transform Service configuration.

If you have more than one Alfresco Transform Core instance (for example a custom implementation), you can add it simply declaring a new bean of type `AlfrescoTransformCoreRenditionProviderLoader`:

.Implementing the AlfrescoTransformCoreRenditionProviderLoader Extension Point
====
[source, java]
----
@Configuration
public class MyAppBeansConfig {

	@Bean
	public ExternalRenditionProviderLoader customAlfrescoTransformCoreRenditionProviderLoader(
		@Value("${custom.alfresco.transform.core.url}") String customAlfrescoTransformCoreUrl,
		@Value("${spring.content.renditions.loaders.maxRetries}") Integer maxRetries,
		@Value("${spring.content.renditions.loaders.timeoutSeconds}") Integer timeoutSeconds, DefaultListableBeanFactory registry) {

		return new AlfrescoTransformCoreRenditionProviderLoader(customAlfrescoTransformCoreUrl, "CustomAlfrescoTransformCore", maxRetries, timeoutSeconds, registry);
    }
}
----
====

The AlfrescoTransformCoreRenditionProviderLoader works with 4 parameters:

1. the service url, used for API calls;
2. the max retries, that is the max attempts number for check if the service is up (default 5, but it's simply overridable adding the property `spring.content.renditions.loaders.maxRetries` to your application.properties);
3. the timeout seconds, that is the max seconds before the timeout in the service availability check (default 5, but it's simply overridable adding the property `spring.content.renditions.loaders.timeoutSeconds` to your application.properties);
4. the DefaultListableBeanFactory for register `RenditionProvider` beans dynamically.

You can also disable the automatic beans loading specifying the property `spring.content.renditions.loaders.active=false` in your application.yml (the default value is true);

== ExternalRenditionProviderLoader Extension Point

If you need to dynamically load beans of type `RenditionProvider` like the Alfresco Transform Core service, you can implement the `ExternalRenditionProviderLoader` interface, defining:

1. the logic for register beans;
2. the loader name;

.Implementing the ExternalRenditionProviderLoader Extension Point
====
[source, java]
----
@Component
public class CustomExternalRenditionProviderLoader implements ExternalRenditionProviderLoader {

    @Override
    public void loadBeans() {
        LOGGER.info("Loading beans for loader {}", getLoaderName());
        ...
    }

    @Override
    public String getLoaderName() {

        return "CustomExternalRenditionProviderLoader";
    }
}
----
====